#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2010 Mark Wong & Open Source Development Labs, Inc.
#

usage()
{
	echo "usage: create-db -h"
	echo "usage: create-db [-p port]"
}

while getopts "hp:" OPT; do
	case ${OPT} in
	h)
		usage
		exit 0
		;;
	p)
		PORT=${OPTARG}
		;;
	esac
done

if [ -z ${PGDATA} ]; then
	echo "PGDATA not defined."
	exit 1
fi

if [ -z ${DBNAME} ]; then
	echo "DBNAME not defined."
	exit 1
fi

if [ ! "x${PORT}" = "x" ]; then
	PORTOPT="-p ${PORT}"
fi

# Create database
echo "Creating database..."
if [ -d ${PGDATA} ]; then
	echo "======================================="
	echo "PGData directory ${PGDATA} already exists"
	echo "Skipping initdb"
	echo "======================================="
else
	initdb -D ${PGDATA} --locale=C || exit 1
fi

if [ ! "x${PORT}" = "x" ]; then
	dbt5-pgsql-start-db -p "-c port=${PORT}"
else
	dbt5-pgsql-start-db
fi

# Give the database a few seconds to get going
sleep 4

createdb ${PORTOPT} -E SQL_ASCII ${DBNAME} || exit 1
createlang ${PORTOPT} plpgsql ${DBNAME} || exit 1

exit 0
