#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2006 Rod Taylor & Open Source Development Lab, Inc.
#               2010 Mark Wong
#

if [ -z ${PGDATA} ]; then
	echo "PGDATA not defined."
	exit 1
fi

# We only need to stop the database if it's running.
if [ -f ${PGDATA}/postmaster.pid ]; then
	pg_ctl -w -D ${PGDATA} stop ${1}
fi
