#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2010 Mark Wong & Open Source Development Labs, Inc.
#               2006 Rilson Nascimento
#

# FIXME: Currently assumes we are loading in the C stored functions.  More
# logic needed to also handle plpgsql if so desired.

while getopts "d:p:q" OPT; do
	case ${OPT} in
	d)
		DBNAME=${OPTARG}
		;;
	p)
		PORT=${OPTARG}
		;;
	q)
		LANGDIR="pgsql"
		;;
	esac
done

if [ ! "x${DBNAME}" = "x" ]; then
	DBNAMEARG="-d ${DBNAME}"
fi

PSQL="psql ${PORTARG} -e ${DBNAMEARG}"
SHAREDIR=`pg_config --sharedir`

# Broker Volume transaction
${PSQL} -f ${SHAREDIR}/contrib/broker_volume.sql || exit 1

# Customer Position transaction
${PSQL} -f ${SHAREDIR}/contrib/customer_position.sql || exit 1

# Data Maintenance transaction
${PSQL} -f ${SHAREDIR}/contrib/data_maintenance.sql || exit 1

# Market Feed transaction
${PSQL} -f ${SHAREDIR}/contrib/market_feed.sql || exit 1

# Market Watch transaction
${PSQL} -f ${SHAREDIR}/contrib/market_watch.sql || exit 1

# Security Detail transaction
${PSQL} -f ${SHAREDIR}/contrib/security_detail.sql || exit 1

# Trade Cleanup transaction
${PSQL} -f ${SHAREDIR}/contrib/trade_cleanup.sql || exit 1

# Trade Lookup transaction
${PSQL} -f ${SHAREDIR}/contrib/trade_lookup.sql || exit 1

# Trade Order transaction
${PSQL} -f ${SHAREDIR}/contrib/trade_order.sql || exit 1

# Trade Result transaction
${PSQL} -f ${SHAREDIR}/contrib/trade_result.sql || exit 1

# Trade Status transaction
${PSQL} -f ${SHAREDIR}/contrib/trade_status.sql || exit 1

# Trade Update transaction
${PSQL} -f ${SHAREDIR}/contrib/trade_update.sql || exit 1
