#!/bin/bash
MYSQL=mysql
DB_NAME=bid

BID_DATA=~/BID_DATA

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${BID_DATA}/User.txt\" \
		INTO TABLE USER FIELDS TERMINATED BY \"|\" ";
echo "finish loading user"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${BID_DATA}/Bidrec.txt\" \
		INTO TABLE BIDREC FIELDS TERMINATED BY \"|\" ";
echo "finish loading bidrec"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${BID_DATA}/Item.txt\" \
		INTO TABLE BIDITEM FIELDS TERMINATED BY \"|\" ";
echo "finish loading biditem"


