#!/bin/bash
MYSQL=mysql
DB_NAME=seats

SEATS_DATA=/home/cong/SEATS_DATA

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${SEATS_DATA}/Country.txt\" \
		INTO TABLE COUNTRY FIELDS TERMINATED BY \"|\" ";
echo "finish loading country"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${SEATS_DATA}/Airport.txt\" \
		INTO TABLE AIRPORT FIELDS TERMINATED BY \"|\" ";
echo "finish loading airport"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${SEATS_DATA}/AirportDistance.txt\" \
		INTO TABLE AIRPORT_DISTANCE FIELDS TERMINATED BY \"|\" ";
echo "finish loading airport_distance"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${SEATS_DATA}/Airline.txt\" \
		INTO TABLE AIRLINE FIELDS TERMINATED BY \"|\" ";
echo "finish loading airline"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${SEATS_DATA}/Customer.txt\" \
		INTO TABLE CUSTOMER FIELDS TERMINATED BY \"|\" ";
echo "finish loading customer"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${SEATS_DATA}/FrequentFlyer.txt\" \
		INTO TABLE FREQUENT_FLYER FIELDS TERMINATED BY \"|\" ";
echo "finish loading frequet_flyer"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${SEATS_DATA}/Flight.txt\" \
		INTO TABLE FLIGHT FIELDS TERMINATED BY \"|\" ";
echo "finish loading flight"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${SEATS_DATA}/FlightInfo.txt\" \
		INTO TABLE FLIGHT_INFO FIELDS TERMINATED BY \"|\" ";
echo "finish loading flight_info"

${MYSQL} ${DB_NAME} -e " LOAD DATA LOCAL INFILE \"${SEATS_DATA}/Reservation.txt\" \
		INTO TABLE RESERVATION FIELDS TERMINATED BY \"|\" ";
echo "finish loading reservation"

