/*
 * 2006 Rilson Nascimento
 *
 * Broker Volume transaction
 * -------------------------
 * This transaction produces a descending list of the total potential 
 * volume generated by a list of brokers for all trade requests in a given sector
 *
 * Based on TPC-E Standard Specification Draft Revision 0.32.2e Clause 3.3.7.
 */

/*
 * Frame 1
 * Broker Volume
 */

CREATE OR REPLACE FUNCTION BrokerVolumeFrame1 (
						IN broker_list	varchar[],
						IN sector_name	varchar) RETURNS SETOF record AS $$
DECLARE
	-- variables
	b_names		varchar;
	rs		RECORD;
BEGIN
	-- Should return 0 to 40 rows
	FOR rs IN
		SELECT	B_NAME,
			sum(TR_QTY * TR_BID_PRICE)::double precision
		FROM	TRADE_REQUEST,
			SECTOR,
			INDUSTRY,
			COMPANY,
			BROKER,
			SECURITY,
			CUSTOMER_ACCOUNT
		WHERE	TR_CA_ID = CA_ID AND
			CA_B_ID = B_ID AND
			TR_S_SYMB = S_SYMB AND
			S_CO_ID = CO_ID AND
			CO_IN_ID = IN_ID AND
			SC_ID = IN_SC_ID AND
			B_NAME = ANY (broker_list) AND
			SC_NAME = sector_name
		GROUP BY B_NAME ORDER BY 2 DESC
	LOOP
		RETURN NEXT rs;
	END LOOP;
END;
$$ LANGUAGE 'plpgsql';

